version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-api
    ports:
      - "3001:3001"
    networks:
      - microservices-net

  frontend:
    build: ./frontend
    container_name: frontend-web
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true
